name: Node CI

on: [push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: pnpm install, build, and test
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build --if-present
          pnpm test
        env:
          CI: true
